[package]
authors = ["Konstantin Stepanov <me@kstep.me>"]
name = "cargo-pkgbuild"
version = "0.1.1"
readme = "README.md"
description = "ArchLinux's PKGBULD generator from Cargo.toml manifest file"
license = "MIT/Apache-2.0"
homepage = "https://github.com/kstep/cargo-pkgbuild"

[dependencies]
rustc-serialize = "0.3.19"
toml = "0.1.30"
